-- ==========================================================
-- Project : End-to-End Data Pipeline
-- Author  : Ajay Patil
-- Stack   : AWS S3 | Snowflake | Snowpipe | Streams | Tasks | Power BI
-- ==========================================================

-- 1. Database & Schema
CREATE DATABASE IF NOT EXISTS AJAY_PROJECT;
USE DATABASE AJAY_PROJECT;

CREATE SCHEMA IF NOT EXISTS SHRUTI;
USE SCHEMA SHRUTI;

-- 2. Warehouse
CREATE OR REPLACE WAREHOUSE ETL_WH
WITH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

USE WAREHOUSE ETL_WH;

-- 3. File Format
CREATE OR REPLACE FILE FORMAT CSV_FMT
TYPE = CSV
COMPRESSION = AUTO
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
EMPTY_FIELD_AS_NULL = TRUE
NULL_IF = ('NULL','null','')
ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- 4. Storage Integration
CREATE OR REPLACE STORAGE INTEGRATION S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<YOUR_ACCOUNT_ID>:role/aws_data'
STORAGE_ALLOWED_LOCATIONS = ('s3://ajay-snow/apple_data/');

DESC STORAGE INTEGRATION S3_INT;

-- 5. External Stage
CREATE OR REPLACE STAGE APP_STAGE
URL='s3://ajay-snow/apple_data/'
STORAGE_INTEGRATION=S3_INT
FILE_FORMAT=CSV_FMT;

LIST @APP_STAGE;

-- 6. Target Table
CREATE OR REPLACE TABLE CUSTOMER(
    CUSTOMER_ID STRING,
    MEMBERSHIP STRING,
    JOINING_YEAR NUMBER
);

-- 7. Initial Load
COPY INTO CUSTOMER
FROM @APP_STAGE
FILES=('customers.csv');

-- 8. Stream (CDC)
CREATE OR REPLACE STREAM CUSTOMER_STREAM
ON TABLE CUSTOMER;

-- 9. Curated Table
CREATE OR REPLACE TABLE CUSTOMER_CURATED AS
SELECT *
FROM CUSTOMER
WHERE JOINING_YEAR >= 2020;

-- 10. Task
CREATE OR REPLACE TASK CUSTOMER_TASK
WAREHOUSE=ETL_WH
SCHEDULE='5 MINUTE'
AS
MERGE INTO CUSTOMER_CURATED C
USING CUSTOMER_STREAM S
ON C.CUSTOMER_ID=S.CUSTOMER_ID
WHEN MATCHED THEN
UPDATE SET
    MEMBERSHIP=S.MEMBERSHIP,
    JOINING_YEAR=S.JOINING_YEAR
WHEN NOT MATCHED THEN
INSERT (CUSTOMER_ID,MEMBERSHIP,JOINING_YEAR)
VALUES (S.CUSTOMER_ID,S.MEMBERSHIP,S.JOINING_YEAR);

ALTER TASK CUSTOMER_TASK RESUME;

-- 11. Snowpipe
CREATE OR REPLACE PIPE CUSTOMER_PIPE
AUTO_INGEST=TRUE
AS
COPY INTO CUSTOMER
FROM @APP_STAGE
FILE_FORMAT=(FORMAT_NAME=CSV_FMT);

-- 12. View
CREATE OR REPLACE VIEW VW_CUSTOMER AS
SELECT *
FROM CUSTOMER_CURATED;

-- 13. Validation
SELECT COUNT(*) AS TOTAL_RECORDS
FROM CUSTOMER;

SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME=>'CUSTOMER',
        START_TIME=>DATEADD(day,-7,CURRENT_TIMESTAMP())
    )
);

SHOW STAGES;
SHOW PIPES;
SHOW TASKS;
SHOW STREAMS;
